### ISSUE TITLE
Uniqueness of records

### ISSUE THREAD

**Issue by amnesia7** [mirego/partisan#16]
Hi,

I was wondering if you were planning on adding a validation to the gem to check uniqueness of records being created so an object can only be followed by another object once. Maybe adding a database unique index as well as the active record uniqueness validation.

**Comment by amnesia7** [comment]
@remiprev should this issue be closed now that the index has been added to the gem or does it need to remain open until the new version gets published or something?

**Comment by remiprev** [comment]
@amnesia7 You’re right, I thought I added some kind of magic text in my commit message (you know, like `Fixes #16`) in my commit message.
