### ISSUE TITLE
NoMethodError: undefined method `followers' for #<User:0x007f8f221fd520>

### ISSUE THREAD

**Issue by jrasanen** [mirego/partisan#18]
I added `acts_as_followable` `acts_as_follower` to User class.

Docs say those define `followers`-method for the class, but I think its actually named `followings` and `follows`.

```ruby
user = User.find(1)
user.followers # NoMethodError: undefined method `followers' for #<User:0x007f8f221fd520>
user.followings # ActiveRecord_Associations_CollectionProxy
user.follows # ActiveRecord_Associations_CollectionProxy
```

**Comment by remiprev** [comment]
Oh, you’re absolutely right. The correct way to get all the records that _follow_ a specific user would be:

```ruby
user = User.find(1)
user.followers_by_type('User')
```

This will return an `ActiveRecord::Relation` containing all users that follow the first user.

The `followings` method returns an `ActiveRecord::Relation` of `Follow` records, which have a `follower` association.

Thanks for spotting this, I’m going to update the `README.md` file!

**Comment by jrasanen** [comment]
Thank you!
